version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:latest
    hostname: keycloak
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: P@ssword!
    # volumes:
    #   - ./certs:/etc/x509/https
